version: '3.8'

services:
  # Наша локальная LLM
  vllm-server:
    image: vllm/vllm-openai:latest
    container_name: qwen_vllm
    # Пробрасываем видеокарту
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - "8000:8000"
    volumes:
      # Кэшируем веса модели на хосте, чтобы не качать их каждый раз при рестарте
      - ~/.cache/huggingface:/root/.cache/huggingface
    command: >
      --model Qwen/Qwen2.5-14B-Instruct-AWQ --quantization awq --max-model-len 4096 --gpu-memory-utilization 0.4
    # 0.4 означает, что vLLM заберет ровно 40% VRAM (~12.8 ГБ), оставив остальное для Whisper
    ipc: host

  # Наш FastAPI бэкенд (Voice Assistant)
  api-server:
    build: .
    container_name: voice_api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - "8001:8001"
    environment:
      # Указываем имя контейнера vLLM, чтобы API знал, куда стучаться
      - LLM_BASE_URL=http://vllm-server:8000/v1
    depends_on:
      - vllm-server
